version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: airflow-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow_db
    ports:
      - "5433:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  airflow:
    image: apache/airflow:2.7.3
    container_name: airflow-web
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow_db
      AIRFLOW__CORE__FERNET_KEY: 'oZcbC2E2QkUe1sGZr4W5g6p8u2q7t9o1'
      AIRFLOW__WEBSERVER__SECRET_KEY: 'airflowsecretkey'
      _PIP_ADDITIONAL_REQUIREMENTS: "pandas psycopg2-binary requests"
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db init &&
               airflow users create --username admin --password admin --firstname Vlad --lastname Popescu --role Admin --email vlad.popescu77@gmail.com &&
               airflow webserver & airflow scheduler"
    depends_on:
      - postgres
