
name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create archive
        run: |
          zip -r retail_sales_analytics_${{ github.ref_name }}.zip . -x "*.git*"
      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: retail_sales_analytics_${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
