version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: fastapi-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dataapi
    ports:
      - "5434:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  api:
    build: .
    container_name: fastapi-api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
