version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  spark:
    image: bitnami/spark:latest
    container_name: spark
    environment:
      - SPARK_MODE=driver
    volumes:
      - ./consumer:/opt/spark-apps/consumer
    depends_on:
      - kafka
    command: ["sleep", "infinity"]

  producer:
    image: python:3.11
    container_name: producer
    volumes:
      - ./producer:/app/producer
    working_dir: /app
    command: bash -c "pip install kafka-python && python /app/producer/kafka_producer.py"
    depends_on:
      - kafka
